---
- hosts: all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
  handlers:
    - import_tasks: scripts/handlers.yml
  tasks:
    - import_tasks: scripts/hardening.yml


- hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: scripts/containers.yml

- hosts: all
  become: true
  tasks:
    - name: Remove temporary provisioning user
      user:
        name: "provisioner"
        state: absent
        remove: true
        force: true
        failed_when: false
